### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by jonnybrooks** [jonnybrooks/migres#1]
- [x] Better error handling
- [x] More expressive cli options e.g. --all to migrate / rollback all, --quiet to suppress logs, --prefix
- [ ] Incremental migration prefixes rather than unix epoch, or make it a cli choice
